apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: eliasonic/online-shopping-monolithic-webapp:latest
        ports:
        - containerPort: 3000
        env:
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: app-secret
        - name: MONGODB_URI
          valueFrom: 
            configMapKeyRef:
              name: mongo-config
              key: mongo-uri

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
